name: Testes Unitários e Integração

on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/cache@v4
        with:
          path: server-main/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('server-main/package-lock.json') }}

      - name: Instalar dependências
        run: npm install
        working-directory: server-main

      - name: Correr testes
        run: npm test
        working-directory: server-main

      - name: Enviar coverage para Codecov   # ← este step novo
        uses: codecov/codecov-action@v4
        with:
          directory: server-main/coverage
